### ISSUE TITLE
Extension cannot be installed Visual Studio SDK v[16.0.28315.86,17.0]

### ISSUE THREAD

**Issue by uppy18** [TargetFrameworkMigrator/TargetFrameworkMigrator#89] opened 2021-01-11 10:06 UTC
Hi,

When trying to use latest extension 1.7.0 in Visual Studio 2017, I get the following error:

Visual Studio SDK : "The prerequisite version specified is invalid"

Expected version as mention in release note is [16.0.28315.86,17.0].

But while upgrading Visual studio maximum available version is 15.9.30 as of 8th Jan 2021.

Please suggest any solution in this scenario.

![image](https://user-images.githubusercontent.com/73994845/104167337-29181f00-5422-11eb-860c-925e923bfbd2.png)

**Comment by bassmaster187** [comment] 2021-04-06 09:06
Same Problem here:

```
06.04.2021 11:03:30 - Die Erweiterung mit der ID TargetFrameworkMigrator..4f7666b9-e62c-46a1-af25-21ab8742ef00 wird nicht für Microsoft Visual Studio Professional 2017 installiert.
06.04.2021 11:03:31 - Die Erweiterung kann für die folgenden Produkte aufgrund fehlender erforderlicher Komponenten nicht installiert werden:
06.04.2021 11:03:31 - 	Microsoft Visual Studio Professional 2017
06.04.2021 11:03:31 - 		-------------------------------------------------------
06.04.2021 11:03:31 - 		Identifier   : Microsoft.VisualStudio.Component.VSSDK
06.04.2021 11:03:31 - 		Name         : Visual Studio SDK
06.04.2021 11:03:31 - 		Version      : [16.0.28315.86,17.0)
06.04.2021 11:03:31 - 		Error        : Die angegebene erforderliche Version ist ungültig.
```

**Comment by gitdash** [comment] 2021-06-03 21:00
I'm also having this issue. Currently running VS 2017 v15.9.12. The error is this:
`03-Jun-21 13:33:59 - Extension cannot be installed to the following products due to missing prerequisites:
03-Jun-21 13:33:59 - 	Microsoft Visual Studio Professional 2017
03-Jun-21 13:33:59 - 		-------------------------------------------------------
03-Jun-21 13:33:59 - 		Identifier   : Microsoft.VisualStudio.Component.VSSDK
03-Jun-21 13:33:59 - 		Name         : Visual Studio SDK
03-Jun-21 13:33:59 - 		Version      : [16.0.28315.86,17.0)
03-Jun-21 13:33:59 - 		Error        : The prerequisite version specified does not match the version installed`

**Comment by SylwesterZarebski** [comment] 2021-06-18 07:39
I think the second one, because even if You have installed VS2019 (i have VS2019 and have the same error), then VS2017 do not have access to internal VSSDK between versions.

**Comment by 304NotModified** [comment] 2021-07-24 22:30
thanks for reporting. Duplicate of #88

**Closed by 304NotModified** 2021-07-24 22:30 UTC
