### ISSUE TITLE
Cannot Install in VS 2019 

### ISSUE THREAD

**Issue by dsseb** [TargetFrameworkMigrator/TargetFrameworkMigrator#84] opened 2020-06-12 08:28 UTC
it just gives me the following installation log 

12.06.2020 10:25:01 - Microsoft VSIX Installer
12.06.2020 10:25:01 - -------------------------------------------
12.06.2020 10:25:01 - vsixinstaller.exe version:
12.06.2020 10:25:01 - 16.5.2047
12.06.2020 10:25:01 - -------------------------------------------
12.06.2020 10:25:01 - Command line parameters:
12.06.2020 10:25:01 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\xxx\Downloads\TargetFrameworkMigrator.vsix
12.06.2020 10:25:01 - -------------------------------------------
12.06.2020 10:25:01 - Microsoft VSIX Installer
12.06.2020 10:25:01 - -------------------------------------------
12.06.2020 10:25:02 - Skipping product Microsoft.VisualStudio.Product.BuildTools (0726c91f) since it does not support extensions
12.06.2020 10:25:02 - Initializing Install...
12.06.2020 10:25:02 - Erweiterungsdetails...
12.06.2020 10:25:02 - 	Identifier         : TargetFrameworkMigrator..4f7666b9-e62c-46a1-af25-21ab8742ef00
12.06.2020 10:25:02 - 	Name               : Target Framework Migrator
12.06.2020 10:25:02 - 	Author             : VHQLabs
12.06.2020 10:25:02 - 	Version            : 1.6.5
12.06.2020 10:25:02 - 	Description        : Change all your .Net projects Target Framework at once
12.06.2020 10:25:02 - 	Locale             : en-US
12.06.2020 10:25:02 - 	MoreInfoURL        : 
12.06.2020 10:25:02 - 	InstalledByMSI     : False
12.06.2020 10:25:02 - 	SupportedFrameworkVersionRange : [4.5,)
12.06.2020 10:25:02 - 
12.06.2020 10:25:02 - 	SignatureState     : Unsigned
12.06.2020 10:25:02 - 	Unterstützte Produkte : 
12.06.2020 10:25:02 - 		Microsoft.VisualStudio.Pro
12.06.2020 10:25:02 - 			Version : [11.0,16.0]
12.06.2020 10:25:02 - 		Microsoft.VisualStudio.Community
12.06.2020 10:25:02 - 			Version : [15.0,16.0)
12.06.2020 10:25:02 - 		Microsoft.VisualStudio.Enterprise
12.06.2020 10:25:02 - 			Version : [15.0,16.0)
12.06.2020 10:25:02 - 
12.06.2020 10:25:02 - 	Verweise           : 
12.06.2020 10:25:02 - 	Voraussetzungen    : 
12.06.2020 10:25:02 - 		-------------------------------------------------------
12.06.2020 10:25:02 - 		Identifier   : Microsoft.VisualStudio.Component.VSSDK
12.06.2020 10:25:02 - 		Name         : Visual Studio SDK
12.06.2020 10:25:02 - 		Version      : [15.0.26208.0,16.0)
12.06.2020 10:25:02 - 
12.06.2020 10:25:02 - Signaturdetails...
12.06.2020 10:25:02 - 	Extension is not signed.
12.06.2020 10:25:02 - 
12.06.2020 10:25:02 - Er wird nach passenden Produkten gesucht...
12.06.2020 10:25:02 - Installiertes Produkt gefunden - Globaler Pfad
12.06.2020 10:25:02 - Installiertes Produkt gefunden - Visual Studio Professional 2019
12.06.2020 10:25:02 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by michaelm7456** [comment] 2020-07-21 23:24
I think I know the cause of this one.

I've tried downloading the Extension for 'Target Framework Migrator' [here.](https://marketplace.visualstudio.com/items?itemName=PavelSamokha.TargetFrameworkMigrator)

And received the below error.
![image](https://user-images.githubusercontent.com/20442719/88116635-ebdc7e00-cbb0-11ea-96ab-07e74fcb18de.png)

And the contents of the log here:

22/07/2020 00:16:43 - Microsoft VSIX Installer
22/07/2020 00:16:43 - -------------------------------------------
22/07/2020 00:16:43 - vsixinstaller.exe version:
22/07/2020 00:16:43 - 16.6.2051
22/07/2020 00:16:43 - -------------------------------------------
22/07/2020 00:16:43 - Command line parameters:
22/07/2020 00:16:43 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Michael\Downloads\TargetFrameworkMigrator.vsix
22/07/2020 00:16:43 - -------------------------------------------
22/07/2020 00:16:43 - Microsoft VSIX Installer
22/07/2020 00:16:43 - -------------------------------------------
22/07/2020 00:16:44 - Initializing Install...
22/07/2020 00:16:44 - Extension Details...
22/07/2020 00:16:44 - 	Identifier         : TargetFrameworkMigrator..4f7666b9-e62c-46a1-af25-21ab8742ef00
22/07/2020 00:16:44 - 	Name               : Target Framework Migrator
22/07/2020 00:16:44 - 	Author             : VHQLabs
22/07/2020 00:16:44 - 	Version            : 1.6.5
22/07/2020 00:16:44 - 	Description        : Change all your .Net projects Target Framework at once
22/07/2020 00:16:44 - 	Locale             : en-US
22/07/2020 00:16:44 - 	MoreInfoURL        : 
22/07/2020 00:16:44 - 	InstalledByMSI     : False
22/07/2020 00:16:44 - 	SupportedFrameworkVersionRange : [4.5,)
22/07/2020 00:16:44 - 
22/07/2020 00:16:44 - 	SignatureState     : Unsigned
22/07/2020 00:16:44 - 	Supported Products : 
22/07/2020 00:16:44 - 		Microsoft.VisualStudio.Pro
22/07/2020 00:16:44 - 			Version : [11.0,16.0]
22/07/2020 00:16:44 - 		Microsoft.VisualStudio.Community
22/07/2020 00:16:44 - 			Version : [15.0,16.0)
22/07/2020 00:16:44 - 		Microsoft.VisualStudio.Enterprise
22/07/2020 00:16:44 - 			Version : [15.0,16.0)
22/07/2020 00:16:44 - 
22/07/2020 00:16:44 - 	References         : 
22/07/2020 00:16:44 - 	Prerequisites      : 
22/07/2020 00:16:44 - 		-------------------------------------------------------
22/07/2020 00:16:44 - 		Identifier   : Microsoft.VisualStudio.Component.VSSDK
22/07/2020 00:16:44 - 		Name         : Visual Studio SDK
22/07/2020 00:16:44 - 		Version      : [15.0.26208.0,16.0)
22/07/2020 00:16:44 - 
22/07/2020 00:16:44 - Signature Details...
22/07/2020 00:16:44 - 	Extension is not signed.
22/07/2020 00:16:44 - 
22/07/2020 00:16:44 - Searching for applicable products...
22/07/2020 00:16:44 - Found installed product - Global Location
22/07/2020 00:16:44 - Found installed product - Visual Studio Community 2019
22/07/2020 00:16:44 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

But the Supported Version in the failed Log shows Visual Studio Versions : **[11.0,16.0]**.

Not **[11.0,17.0]** as we would expect and which the codebase currently has.

I suspect this is because the '**Target Framework Migrator**' Extension was last published on 13th June 2017, and there have been subsequest updates to this repository that have not been published to the Visual Studio Extension Gallery.

<img width="717" alt="Target Framework Migrator" src="https://user-images.githubusercontent.com/20442719/88116733-2f36ec80-cbb1-11ea-8d8d-ee4e01754cb6.png">

To verify this I can confirm that building the Extension locally and Installing it was successful, because the .VSIX manifest file has the correct Version Number range of **[11.0,17.0]**

<img width="328" alt="VSIX Local Install Success" src="https://user-images.githubusercontent.com/20442719/88116885-95bc0a80-cbb1-11ea-814b-5f2397ac1b16.png">

Publishing the latest iteration of this repo should fix the issue unless there are any other problems with '**master**' branch.

Hope this helps!

**Comment by 304NotModified** [comment] 2020-11-19 20:24
This should be fixed in 1.7!

**Closed** 2021-07-24 22:22 UTC
