### ISSUE TITLE
InvalidParameter (index)

### ISSUE THREAD

**Issue by kiebor** [TargetFrameworkMigrator/TargetFrameworkMigrator#47] opened 2018-03-29 11:47 UTC
VS version: 15.6.4
On opening the tool and alert dialogue is presented with the following content:
"InvalidParameter
Parameter name:index"

The offending solution contains several project types, including:
console
mvc
web api
npm (ts project)

Outside of the solution the tool window opens as expected.

I've looked over several other logged issues and this same dialogue is thrown when an unrecognised project type is in the solution. Previous culprits appear to have been setup and unit test projects -- my assumption is that the .njsproj is to blame in my particular scenario(?)

**Comment by kiebor** [comment] 2018-03-29 11:54
#46 
#36

**Comment by jacargentina** [comment] 2018-04-12 13:50
I've found that .wix projects also throw the same error. Same workaround to make it work

**Comment by fan-jiang** [comment] 2018-04-19 18:34
I've found that the same error is caused by C++ projects (`.vcxproj`) included the solution. Having to unload these projects to make it work.

**Comment by antibarbie** [comment] 2018-09-24 13:50
Great ! it fails on all .vcxproj and .wixproj ... so I just have to unload all my solution projects and it opens ! Except that all the unloaded projects are now excluded from the target migration.
This issue is a must fix, it just does not work  !

**Comment by tomRedox** [comment] 2019-02-16 14:29
Same issue for us with a solution containing a mixture of projects including web api, winforms, vb and c# libraries and MS installer projects

**Comment by 304NotModified** [comment] 2021-07-24 22:35
I assume this is fixed in 1.7. If not, please open a new issue

**Closed by 304NotModified** 2021-07-24 22:35 UTC
